# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c13d638b12f2fd9965ad969b68704feafa0b568f9fc5d138e51c4343e4c302df92c7d0f5d646a440a6d2067fc5d1a2fb22d1f50eb08361a6174bfc56473afeea

test:
  secret_key_base: 28ae777f2564b2c0b520cee5f9c1c5dcbf8481042a680c4b5342d85a9f15fa3d1085ad101efbda8fb30f33e11463bb8f43220014b8064fc8b1685f6c9315580b

staging:
 secret_key_base : 509982b0878613edb6cb8a9155bf139b
 
production:
 secret_key_base : <%= ENV["PRODUCTION_SECRET_KEY_BASE" ] %>
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
